### ISSUE TITLE
unable to run MEplot

### ISSUE THREAD

**Issue by avilella** [joshuabhk/methylsuite#1]
python ./MEplot2.py --help

```
Traceback (most recent call last):
  File "./MEplot2.py", line 13, in <module>
    from call.meplot import GenomeMethylationCounter
  File "/data/home/user/methylsuite/call/meplot.py", line 9, in <module>
    from seq.fastq import quality_string2score
  File "/data/home/user/methylsuite/seq/fastq.py", line 2, in <module>
    from statlib.stats import mean, stdev
ImportError: No module named statlib.stats
```

Any ideas?

**Comment by joshuabhk** [comment]
I used python statistical library statlib.
I am sorry it is not specified in the readme.

You can install the library by following command in Unix/Linux or mac.

pip install --user statlib

Best,

Bong-Hyun

**Comment by Joeblack83** [comment]
May I use MEplot2.py with Bam file?

**Comment by joshuabhk** [comment]
Yes, you can. It works with bam or Sam files. But for faster access the
files need to be sorted and indexed.

Let me know if it works for you.

Best,

Bong-Hyun
